apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  project: test
  source:
    repoURL: https://github.com/sander-1105/traefik-kubernetes-helm.git
    targetRevision: feature/helm
    path: applications/test1
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true